# Generated by Django 5.1.7 on 2025-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_transaction_quantity_wallet_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='wallet',
            new_name='token',
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
