# Generated by Django 5.1.7 on 2025-04-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
