# Generated by Django 5.1.7 on 2025-04-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_alter_transaction_amount_alter_transaction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=25),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=6, max_digits=60),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=60),
        ),
    ]
