# Generated by Django 5.1.7 on 2025-04-11 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_alter_transaction_amount_alter_transaction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='crypto.wallet'),
        ),
    ]
