# Generated by Django 5.1.7 on 2025-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0010_alter_transaction_amount_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=60),
        ),
    ]
