# Generated by Django 5.1.7 on 2025-04-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0012_alter_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
    ]
