# Generated by Django 5.1.7 on 2025-04-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_rename_wallet_transaction_token_transaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
