# Generated by Django 5.1.7 on 2025-04-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0008_alter_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(max_length=64),
        ),
    ]
