# Generated by Django 5.1.7 on 2025-04-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0011_alter_transaction_quantity_alter_wallet_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
