# Generated by Django 5.1.7 on 2025-04-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0013_wallet_average_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='session_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='session_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=25),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=60),
        ),
    ]
