# Generated by Django 5.1.7 on 2025-04-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0015_alter_wallet_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='return_on_investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
    ]
