# Generated by Django 5.1.7 on 2025-04-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0016_wallet_return_on_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
