# Generated by Django 5.1.7 on 2025-04-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0017_alter_wallet_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cogs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
    ]
